# .github/dependabot.yaml

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/src/ui"
    schedule:
      interval: "daily"
    # Disable version updates for dependencies, only security updates
    open-pull-requests-limit: 0
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    # Disable version updates for dependencies, only security updates
    open-pull-requests-limit: 0
