ci:
  autofix_commit_msg: "style: pre-commit.ci auto fix"
  autoupdate_commit_msg: "chore(deps): pre-commit autoupdate"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
        name: Check Python AST
      - id: check-toml
        name: Check TOML
      - id: check-yaml
        name: Check YAML
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
            src/ui/static/
          )
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.21.2
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
  - repo: https://github.com/pycqa/isort
    rev: 5.9.2
    hooks:
      - id: isort
        name: Sort imports (core)
        additional_dependencies: [toml]
        files: ^src/
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
        name: Format code (Python)
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.2
    hooks:
      - id: prettier
        name: Format other code (CSS, HTML, JS, MD, TOML, YAML)
        additional_dependencies:
          - prettier@2.3.2
          - "prettier-plugin-toml"
        types: [file]
        files: \.(css|html|js|markdown|md|toml|yaml|yml)$
        exclude: |
          (?x)^(
            src/ui/static/dist
          )
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v5.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies:
          - "@vidavidorra/commitlint-config"
          - "commitlint-plugin-function-rules"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        name: Run mypy
        additional_dependencies:
          - "sqlalchemy[mypy]"
          - "types-all"
        files: ^src/
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [flake8-typing-imports==1.10.0]
        exclude: |
          (?x)^(
            tests/|
            ci/
            )
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
      - id: autopep8
        exclude: |
          (?x)^(
            tests/|
            ci/
            )
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.17.0
    hooks:
      - id: setup-cfg-fmt
