repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-ast
        name: Check Python AST
      - id: check-toml
        name: Check TOML
      - id: check-yaml
        name: Check YAML
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.7.0
    hooks:
      - id: isort
        name: Sort imports (core)
        additional_dependencies: [toml]
        files: ^core/
        args: ["--settings-path", "core"]
  - repo: https://github.com/pycqa/isort
    rev: 5.7.0
    hooks:
      - id: isort
        name: Sort imports (tracing)
        additional_dependencies: [toml]
        files: ^tracing/
        args: ["--settings-path", "tracing"]
  - repo: https://github.com/pycqa/isort
    rev: 5.7.0
    hooks:
      - id: isort
        name: Sort imports (ui)
        additional_dependencies: [toml]
        files: ^ui/
        args: ["--settings-path", "ui"]
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        name: Format code (Python)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        name: Format code (CSS, HTML, TOML, YAML)
        types: [file, javascript, jsx, ts, tsx, html, css, toml, yaml, json]
        additional_dependencies: ["prettier-plugin-toml"]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v4.1.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
