repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-ast
        name: Check Python AST
      - id: check-toml
        name: Check TOML
      - id: check-yaml
        name: Check YAML
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
            ui/ui/static/
          )
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: Sort imports (root)
        additional_dependencies: [toml]
        exclude: |
          (?x)^(
            ci/|
            core/|
            detection/|
            docs/|
            tracing/|
            ui/
          )
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: Sort imports (core)
        additional_dependencies: [toml]
        files: ^core/
        args: ["--settings-path", "core"]
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: Sort imports (detection)
        additional_dependencies: [toml]
        files: ^detection/
        args: ["--settings-path", "detection"]
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: Sort imports (tracing)
        additional_dependencies: [toml]
        files: ^tracing/
        args: ["--settings-path", "tracing"]
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: Sort imports (ui)
        additional_dependencies: [toml]
        files: ^ui/
        args: ["--settings-path", "ui"]
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        name: Format code (Python)
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.0.0
    hooks:
      - id: pydocstyle
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        name: Format other code (CSS, HTML, JS, MD, TOML, YAML)
        additional_dependencies: ["prettier-plugin-toml"]
        types: [file]
        files: \.(css|html|js|markdown|md|toml|yaml|yml)$
        exclude: |
          (?x)^(
            ui/ui/static/dist
          )
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v4.1.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.902
    hooks:
      - id: mypy
        name: Run mypy (root)
        additional_dependencies: [types-all]
        exclude: |
          (?x)^(
            ci/|
            core/|
            detection/|
            docs/|
            tracing/|
            ui/
          )
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.902
    hooks:
      - id: mypy
        name: Run mypy (core)
        additional_dependencies: [types-all]
        files: ^core/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.902
    hooks:
      - id: mypy
        name: Run mypy (ui)
        additional_dependencies: [types-all]
        files: ^ui/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.902
    hooks:
      - id: mypy
        name: Run mypy (tracing)
        additional_dependencies: [types-all]
        files: ^tracing/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.902
    hooks:
      - id: mypy
        name: Run mypy (detection)
        additional_dependencies: [types-all]
        files: ^detection/
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [flake8-typing-imports==1.10.0]
        exclude: |
          (?x)^(
            tests/|
            (core|ui|tracing|detection)/tests/
            )
