---
ci:
  autofix_commit_msg: "style: pre-commit.ci auto fix"
  autoupdate_commit_msg: "chore(deps): pre-commit autoupdate"

exclude: ^src/vendor/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
        name: Check Python AST
      - id: check-toml
        name: Check TOML
      - id: check-yaml
        name: Check YAML
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
            src/ui/static/
          )
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
  - repo: https://github.com/pycqa/isort
    rev: 5.11.4
    hooks:
      - id: isort
        name: Sort imports (core)
        additional_dependencies: [toml]
        files: ^src/
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        name: Format code (Python)
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.2.0
    hooks:
      - id: pydocstyle
        exclude: ^scripts/
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        name: Format other code (CSS, HTML, JS, MD, TOML, YAML)
        additional_dependencies:
          - prettier@2.6.0
          - "prettier-plugin-toml"
        types: [file]
        files: \.(css|html|js|markdown|md|toml|yaml|yml)$
        exclude: |
          (?x)^(
            src/ui/static/dist
          )
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.3.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies:
          - "@vidavidorra/commitlint-config"
          - "commitlint-plugin-function-rules"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        name: Run mypy
        additional_dependencies:
          - "sqlalchemy[mypy]"
          - "types-all"
          # XXX: type issue with request.post files argument
          # https://github.com/python/typeshed/issues/7724
          - "types-requests==2.27.20"
        files: ^src/
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-typing-imports==1.14.0]
        exclude: |
          (?x)^(
            tests/|
            ci/
            )
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.1
    hooks:
      - id: autopep8
        exclude: |
          (?x)^(
            tests/|
            ci/
            )
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.2.0
    hooks:
      - id: setup-cfg-fmt
