[tool.poetry]
name = "code"
version = "0.1.0"
description = """
Application to detect fish and generate a report viewable
inside an iterface before being exported as raw data.
"""
authors = [
"Birger Johan Nordølum",
"Eirik Osland Lavik",
"Kristian André Dahl Haugen",
"Tom-Ruben Traavik Kvalvaag"
]
packages = [
    { include = "./ui" },
    { include = "./core" },
    { include = "./tracing" },
    { include = "./detection" },
]


[tool.poetry.dependencies]
python = "^3.7"
core = {path = "core"}
tracing = {path = "tracing"}
app = {path = "ui"}
detection = {path = "detection"}

[tool.poetry.dev-dependencies]
debugpy = "^1.2.1"
pip = "^21.0.1"
pytest = "^6.2.2"
pytest-cov = "^2.11.1"
coverage = {extras = ["toml"], version = "^5.4"}
pre-commit = "^2.10.1"
isort = "^5.7.0"
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
line_length = 80
multi_line_output = 3

[tool.black]
line-length = 80
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
/(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | \.pytest_cache
    | \.ipynb_checkpoints
    | __pycache__
    | _build
    | buck-out
    | build
    | dist
    | rapport
    | opppgave
    | hdr-bilder
    | venv
    | node_modules
    | README.md
)/
'''
verbose = true

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]
log_cli = "True"
log_level = "DEBUG"
