[project]
name = "nina"
description = '''
Application to detect, track and calculate statistics of objects in video.
'''
authors = [
  "Birger Johan Nordølum",
  "Eirik Osland Lavik",
  "Kristian André Dahl Haugen",
  "Tom-Ruben Traavik Kvalvaag"
]
license = "GPL-3.0"

[build-system]
requires = ["setuptools >= 35.0.2", "setuptools_scm >= 2.0.0, <3"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
line_length = 80
multi_line_output = 3

[tool.black]
line-length = 80
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.pytest_cache
  | __pycache__
  | _build
  | buck-out
  | build
  | dist
  | venv
  | node_modules
  | README.md
)/
'''
verbose = true

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q -v --ignore=ci --import-mode=importlib"
testpaths = ["tests"]
filterwarnings = [
  'ignore:the imp module is deprecated:DeprecationWarning',
  'ignore:"@coroutine" decorator is deprecated:DeprecationWarning',
  'ignore:Named tensors and all their associated APIs:UserWarning'
]
log_cli = "False"
log_level = "INFO"
norecursedirs = [".git", ".tox", ".env", "dist", "build"]
python_files = ["test_*.py", "*_test.py", "tests.py"]

[tool.coverage.run]
branch = true
source = ["src"]
omit = ["*/.tox/*", "*/__main__.py", "*/setup.py", "*/.venv*/*", "*/venv*/*"]

[tool.coverage.report]
show_missing = true
skip_covered = false

[tool.tox]
legacy_tox_ini = '''
[tox]
envlist = py{38,39}-{integration,unit},
          coverage
isolated_build = True
skipsdist = True

[testenv]
deps =
    -e .[testing]
setenv =
    COVERAGE_FILE = {env:COVERAGE_FILE:{toxworkdir}/.coverage.{envname}}
commands =
    integration: coverage run -p -m pytest tests/integration {posargs}
    unit: coverage run -p -m pytest tests/unit {posargs}

[testenv:coverage]
deps = coverage[toml] >= 5.0
skip_install = True
setenv =
    COVERAGE_FILE = {env:COVERAGE_FILE:{toxworkdir}/.coverage}
commands = coverage combine
           coverage report -m
           coverage xml
depends = py39-{integration,unit}
'''
