#!/usr/bin/env python3


class Person:
    name = ""
    age = 0

    def __init__(self, name: str, age: int) -> None:

        self.name = name
        self.age = age

    def get_name(self) -> str:
        return self.name

    def get_age(self) -> int:
        return self.age

    def pretty_print(self) -> None:
        print(f"Name: {self.name}\n\tAge: {self.age}")


def foo() -> int:
    a = 0
    print(a)
    a = find_a()
    for x in range(10):
        a += x
        print(a)
    return a


def find_a() -> int:
    return 50


a = foo()

p1 = Person("kuk", 20)

p1.pretty_print()

a = 0
for x in range(5):
    a += 5 * x


people = []

names = ["hans", "are", "ole", "tom"]

for name, age in zip(names, range(len(names) + 1)):
    people.append(Person(name, age))

for person in people:
    person.pretty_print()


p2 = Person("eple", 5)
