default:
  tags:
    - bachelor
  image: registry.gitlab.com/hitchhikers/container-images/python-quality:latest

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID

stages:
  - prep
  - style
  - quality
  - test

variables:
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip
  POETRY_CACHE_DIR: $CI_PROJECT_DIR/.cache/poetry
  POETRY_VIRTUALENVS_CREATE: "true"
  POETRY_VIRTUALENVS_IN_PROJECT: "false"
  POETRY_VIRTUALENVS_PATH: $CI_PROJECT_DIR/.cache/poetry/venv

.cache_settings:
  cache:
    key: $CI_COMMIT_REF_SLUG-$PIPELINE_ROOT
    paths:
      - .cache/pip
      - .cache/poetry
      - poetry.lock

build_cache:
  stage: prep
  extends: .cache_settings
  script:
    - poetry install
  variables:
    GIT_DEPTH: "3"

style:
  stage: style
  script:
    - isort --check --diff ./*.py
    - black --check --diff ./*.py
  cache: {}

docs:
  stage: style
  script:
    - pydocstyle ./*.py
  allow_failure: true
  cache: {}

pyright:
  stage: quality
  extends: .cache_settings
  before_script:
    - poetry install
  script:
    - poetry run pyright ./*.py
  cache:
    policy: pull

tests:
  stage: test
  extends: .cache_settings
  before_script:
    - poetry install
  script:
    - poetry run pytest
  cache:
    policy: pull
