runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Build UI
      shell: bash
      run: |
        set -euxo pipefail
        cd src/ui
        npm ci --no-audit
        npm run build:prod
