---
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: |
          - cwd: src/ui
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: pnpm
        cache-dependency-path: src/ui
    - name: Build UI
      shell: bash
      run: |
        set -euxo pipefail
        cd src/ui
        pnpm install
        pnpm run build:prod
