name: Lint Commits
on: pull_request

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npm install --save-dev @vidavidorra/commitlint-config
      - uses: wagoid/commitlint-github-action@v4.1.12
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules
