name: Run Quality Suit

on:
  pull_request:
    paths:
      - "src/**"
      - "tests/**"

jobs:
  style:
    name: Check style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install Base Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade black isort
      - name: python-isort
        run: isort --check --diff .
      - name: python-black
        run: black --check --diff .

  docs:
    name: Check documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install Base Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pydocstyle
      - name: Check documentation
        run: pydocstyle
    continue-on-error: true

  tests:
    name: Tests (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    needs: [style, docs]
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Base Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --upgrade tox
      - name: Run Tests (Tox)
        run: tox -e py
      - uses: 5monkeys/cobertura-action@master
        name: Upload Coverage Report
        if: ${{ matrix.python-version == 3.9}}
        with:
          path: coverage.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 75
          fail_below_threshold: false
