---
name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - ".github/**"
      - "!.github/actions/build-ui/**"
      - "!.github/workflows/test-ui.yaml"
      - "pyproject.toml"
      - "src/**"
      - "tests/**"
      - "!src/ui/package.json"
      - "!src/ui/package-lock.json"
      - "!src/ui/static/**"
  workflow_dispatch:

jobs:
  tests:
    name: Python ${{ matrix.python-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache torch-hub downloads
        uses: actions/cache@v3
        with:
          path: ~/.cache/torch
          key: ${{ runner.os }}-torch-hub
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Base Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --upgrade tox virtualenv
      - name: Download weights
        run: |
          python -m scripts.download_weights
      - name: Run tests on ${{ matrix.os }} with python ${{matrix.python-version }}
        run: |
          tox -e py
      - name: Make coverage report
        run: |
          tox -e coverage
