---
name: build and test ui

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - ".github/actions/build-ui"
      - ".github/workflows/test-ui.yaml"
      - "src/ui/package.json"
      - "src/ui/pnpm-lock.yaml"
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - cwd: src/ui
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - run: |
          pnpm -C src/ui run build:dev
      - run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --upgrade tox virtualenv
      - run: |
          python -m scripts.download_weights
      - run: |
          tox -e ui
